---
driver:
  name: lxd_cli
## docker.io need specificl profile else 'PermissionError: [Errno 13] Permission denied: '/sys/kernel/security/apparmor/profiles''
## https://www.stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/
  profile: [ default, docker ]
  config:
    security.privileged: true

transport:
  name: sftp
## try to avoid random "TIMING: scp async upload (Kitchen::Transport::Ssh)"
## default timeout 15s, alternate sftp/kitchen-sync
#transport:
#  name: ssh
#  keepalive: true
#  keepalive_interval: 5
#  timout: 30

driver_config:
  customize:
#  cpus: 2
  memory: 1024

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_cfg_path: test/vagrant/ansible.cfg
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    attributes:

