---

- name: Unarchive densityscout
  unarchive:
    src: /usr/local/share/Toolset/densityscout_build_45_linux.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    exclude:
      - license.txt
      - lin32/densityscout
    extra_opts: -j
