---

- name: Unarchive densityscout
  ansible.builtin.unarchive:
    src: /usr/local/share/Toolset/densityscout_build_45_linux.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    creates: /usr/local/bin/lin64/densityscout
    exclude:
      - license.txt
      - lin32/densityscout
# this messes up with ansible detection
#   extra_opts: -j
#   unsafe_writes: yes

- name: Symlink densityscout
  ansible.builtin.file:
    src: /usr/local/bin/lin64/densityscout
    dest: /usr/local/bin/densityscout
    mode: '0755'
    state: link
