---
# https://airbus-cyber-security.com/mounting-bitlocker-volumes-linux/

- name: Add git safe.directory
  community.general.git_config:
    scope: global
    name: safe.directory
    value: /usr/local/share/Toolset/dislocker
    state: present

- name: git clone dislocker
  ansible.builtin.git:
    repo: https://github.com/Aorimn/dislocker.git
    dest: "{{ siftrem_toolsetdir }}/dislocker"
    version: "{{ dislocker_version | default('f9674c462c06ba47edb468fd1951b3707a3b3b89') }}"

- name: Ensure dislocker dependencies are present
  ansible.builtin.apt:
    name:
      - gcc
      - cmake
      - make
      - libfuse-dev
      - libmbedtls-dev
      - ruby-dev
  register: pkg_result
  until: pkg_result is success

- name: build dislocker
  ansible.builtin.command: "{{ item.c }}"
  args:
    chdir: "{{ siftrem_toolsetdir }}/dislocker"
    creates: "{{ item.t }}"
  with_items:
    - { c: 'cmake .', t: "{{ siftrem_toolsetdir }}/dislocker/Makefile" }
    - { c: make, t: "{{ siftrem_toolsetdir }}/dislocker/src/dislocker-fuse" }

- name: install dislocker
  ansible.builtin.command: make install
  args:
    chdir: "{{ siftrem_toolsetdir }}/dislocker"
    creates: "/usr/local/bin/dislocker"
