---
# https://airbus-cyber-security.com/mounting-bitlocker-volumes-linux/

- name: git clone dislocker
  git:
    repo: https://github.com/Aorimn/dislocker.git
    dest: "{{ siftrem_toolsetdir }}/dislocker"
    version: "{{ dislocker_version | default('6c70382ce68da0e06fcfce576a88b821e4b69077') }}"

- name: Ensure dislocker dependencies are present
  apt:
    name:
      - gcc
      - cmake
      - make
      - libfuse-dev
      - libmbedtls-dev
      - ruby-dev
  register: pkg_result
  until: pkg_result is success

- name: build dislocker
  command: "{{ item.c }}"
  args:
    chdir: "{{ siftrem_toolsetdir }}/dislocker"
    creates: "{{ item.t }}"
  with_items:
    - { c: 'cmake .', t: "{{ siftrem_toolsetdir }}/dislocker/Makefile" }
    - { c: make, t: "{{ siftrem_toolsetdir }}/dislocker/src/dislocker" }

- name: install dislocker
  command: make install
  args:
    chdir: "{{ siftrem_toolsetdir }}/dislocker"
    creates: "/usr/local/bin/dislocker"
