---

- name: Ensure ioc directory exists
  ansible.builtin.file:
    dest: "{{ siftrem_toolsetdir }}/ioc"
    state: directory
    mode: '0755'

- name: Alienvault repository - IOC in malware_analysis
  ansible.builtin.git:
    repo: https://github.com/AlienVault-Labs/AlienVaultLabs.git
    dest: "{{ siftrem_toolsetdir }}/ioc/AlienVaultLabs"
    version: "{{ siftrem_alienvaultlabs_version | default('347a57b31829b6f8e3280e0fd6a0ed49e5453c67') }}"
