---

## fails under lxd+systemd, https://github.com/ansible/ansible-modules-core/issues/5582
- name: set hostname
  hostname: name={{ siftrem_hostname }}
  when: siftrem_hostname is defined
  ignore_errors: true
- name: Add new hostname in /etc/hosts (local resolv)
  replace:
    "dest='/etc/hosts' regexp='^127.0.0.1       localhost' replace='127.0.0.1       localhost {{ siftrem_hostname }}'"
  when: siftrem_hostname is defined

- name: Restrict sshd config
  lineinfile: dest=/etc/ssh/sshd_config regexp="{{ item.regexp }}" line="{{ item.line }}" backup=yes
  with_items:
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin without-password' }

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: check ruby spec permissions
  file: "dest=/home/{{ sift_user }}/.gem/specs state=directory mode=0755 owner={{ sift_user }}"

## https://answers.launchpad.net/ubuntu/+source/snort/+question/262496
- name: Ubuntu | snort noninteractive settings - dir
  file: dest=/etc/snort state=directory mode=0755
- name: Ubuntu | snort noninteractive settings - conf
  lineinfile: dest=/etc/snort/snort.debian.conf line="{{ item }}" mode=0755 backup=yes create=yes
  with_items:
    - 'DEBIAN_SNORT_HOME_NET="any"'
    - "DEBIAN_SNORT_INTERFACE=\"{{ __ubuntu_if }}\""
- name: Check current network interfaces
  command: ip addr
  register: ipaddr
  changed_when: false
- name: Current network interfaces
  debug: var=ipaddr.stdout_lines

- name: Debian | Extra packages install
  apt:
    name: "{{ siftrem_extra_pkgs + __ubuntu_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: pkg_result
  until: pkg_result is success

- include: ramdisk.yml
  when: ramdisk_path is defined and ramdisk_size is defined

- name: Debian | open-vm-tools install
  apt: name=open-vm-tools state=present
  when: vm|bool
  register: pkg_result
  until: pkg_result is success

- name: Debian | Remove some packages
  apt:
    name:
      - rpcbind
      - xterm
#      - netcat-traditional
      - cups-client
    state: absent
  register: pkg_result
  until: pkg_result is success

- name: Review some limits
  lineinfile:
    dest: /etc/security/limits.d/openfiles
    regexp: "^{{ sift_user }}\t\thard\tnofiles\t\t2048"
    line: "{{ sift_user }}\t\thard\tnofiles\t\t2048"
    state: present
    create: yes

## Extra tools
- name: create toolset root dir
  file: dest={{ siftrem_toolsetdir }} mode=0755 owner={{ sift_user }} state=directory

- name: git clone extra tools
  git:
    repo: "{{ item }}"
    dest: "{{ siftrem_toolsetdir }}/{{ item | basename }}"
    version: HEAD
    update: no
    force: no
  with_items: "{{ siftrem_extra_git }}"
  become: yes
  become_user: "{{ sift_user }}"

- name: python build extra tools
  command: "python setup.py install"
  args:
    chdir: "{{ siftrem_toolsetdir }}/{{ item }}"
  with_items: "{{ siftrem_extra_git_python_build }}"
  become: yes

- name: download {{ item.url | basename }}
  get_url:
    url: "{{ item.url }}"
    dest: "{{ siftrem_toolsetdir }}/{{ item.url | basename }}"
    mode: '0400'
    owner: "{{ sift_user }}"
    sha256sum: "{{ item.s }}"
    validate_certs: "{{ item.v | default(true) }}"
  with_items: "{{ siftrem_extra_dl }}"
  ignore_errors: true

- name: Extra pip install with version
  pip:
    name: "{{ item.n }}"
    version: "{{ item.v }}"
    state: present
    executable: pip3
  with_items: "{{ siftrem_extra_pip_version }}"

- name: Extra pip install
  pip:
    name: "{{ siftrem_extra_pip }}"
    state: present
    executable: pip3

- name: Ensure casperjs is present
  npm:
    name: casperjs
    path: "{{ siftrem_toolsetdir }}/casperjs"
  ignore_errors: true
  register: pkg_result
  until: pkg_result is success

- include: yara-signature.yml
  become: yes
  become_user: "{{ sift_user }}"
- include: iocrepository.yml
  become: yes
  become_user: "{{ sift_user }}"

- include: regripper.yml
- include: powershell.yml
- include: maltego.yml
- include: powershell-core.yml
- include: dislocker.yml
- include: peda.yml
- include: guymager.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int > 16
