---

## fails under lxd+systemd, https://github.com/ansible/ansible-modules-core/issues/5582
- name: set hostname
  ansible.builtin.hostname: name={{ siftrem_hostname }}
  when: siftrem_hostname is defined
- name: Add new hostname in /etc/hosts (local resolv)
  ansible.builtin.replace:
    "dest='/etc/hosts' regexp='^127.0.0.1       localhost' replace='127.0.0.1       localhost {{ siftrem_hostname }}'"
  when: siftrem_hostname is defined

- name: Restrict sshd config
  ansible.builtin.lineinfile: dest=/etc/ssh/sshd_config regexp="{{ item.regexp }}" line="{{ item.line }}" backup=yes
  with_items:
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin without-password' }

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: check ruby spec permissions
  ansible.builtin.file: "dest=/home/{{ sift_user }}/.gem/specs state=directory mode=0755 owner={{ sift_user }}"

## https://answers.launchpad.net/ubuntu/+source/snort/+question/262496
- name: Ubuntu | snort noninteractive settings - dir
  ansible.builtin.file: dest=/etc/snort state=directory mode=0755
- name: Ubuntu | snort noninteractive settings - conf
  ansible.builtin.lineinfile:
    dest: /etc/snort/snort.debian.conf
    line: "{{ item }}"
    mode: '0755'
    backup: yes
    create: yes
  with_items:
    - 'DEBIAN_SNORT_HOME_NET="any"'
    - "DEBIAN_SNORT_INTERFACE=\"{{ __ubuntu_if }}\""
- name: Check current network interfaces
  ansible.builtin.command: ip addr
  register: ipaddr
  changed_when: false
- name: Current network interfaces
  ansible.builtin.debug: var=ipaddr.stdout_lines

- name: Debian | Extra packages install
  ansible.builtin.apt:
    name: "{{ siftrem_extra_pkgs + __ubuntu_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: pkg_result
  until: pkg_result is success

- import_tasks: ramdisk.yml
  when: ramdisk_path is defined and ramdisk_size is defined

- name: Debian | open-vm-tools install
  ansible.builtin.apt: name=open-vm-tools state=present
  when: vm|bool
  register: pkg_result
  until: pkg_result is success

- name: Debian | Remove some packages
  ansible.builtin.apt:
    name:
      - rpcbind
      # - netcat-traditional
      - cups-client
    state: absent
  register: pkg_result
  until: pkg_result is success

- name: Review some limits
  ansible.builtin.lineinfile:  # noqa no-tabs
    dest: /etc/security/limits.d/openfiles
    regexp: "^{{ sift_user }}\t\thard\tnofiles\t\t2048"
    line: "{{ sift_user }}\t\thard\tnofiles\t\t2048"
    mode: '0644'
    state: present
    create: yes

## Extra tools
- name: create toolset root dir
  ansible.builtin.file: dest={{ siftrem_toolsetdir }} mode=0755 owner={{ sift_user }} state=directory

- name: git clone extra tools
  ansible.builtin.git:
    repo: "{{ item.r }}"
    dest: "{{ siftrem_toolsetdir }}/{{ item.r | basename }}"
    version: "{{ item.v }}"
    update: no
    force: no
  with_items: "{{ siftrem_extra_git }}"
  become: yes
  become_user: "{{ sift_user }}"

- name: python build extra tools  # noqa 301
  ansible.builtin.command: "python3 setup.py install"
  args:
    chdir: "{{ siftrem_toolsetdir }}/{{ item.d }}"
    creates: "{{ item.t }}"
  with_items: "{{ siftrem_extra_git_python_build }}"
  become: yes

- name: extra downloads
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.d | default(siftrem_toolsetdir + '/' + item.url | basename) }}"
    mode: "{{ item.m | default('0400') }}"
    owner: "{{ sift_user }}"
    checksum: "{{ item.s | default(omit) }}"
    validate_certs: "{{ item.v | default(true) }}"
  register: dl_result
  until: dl_result is success
  with_items: "{{ siftrem_extra_dl }}"

- name: Extra pip install
  ansible.builtin.pip:
    name: "{{ siftrem_extra_pip }}"
    state: present
    executable: pip3

- name: Ensure casperjs is present
  npm:
    name: casperjs
    path: "{{ siftrem_toolsetdir }}/casperjs"
  register: pkg_result
  until: pkg_result is success

- import_tasks: yara-signature.yml
  become: yes
  become_user: "{{ sift_user }}"
- import_tasks: iocrepository.yml
  become: yes
  become_user: "{{ sift_user }}"

- import_tasks: regripper.yml
- import_tasks: powershell-empire.yml
- import_tasks: maltego.yml
  when: siftrem_maltego_enable
- import_tasks: powershell-core.yml
  when: siftrem_powershell_enable
- import_tasks: dislocker.yml
- import_tasks: peda.yml
- import_tasks: guymager.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int > 16

- import_tasks: densityscout.yml

- import_tasks: didierstevenssuite.yml

- import_tasks: networkminer.yml
  when: siftrem_networkminer_enable

- import_tasks: azurestorage.yml
  when: siftrem_azurestorage_enable

- name: Add Applications desktop shortcuts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/share/applications/
    mode: '0644'
  with_items: "{{ siftrem_desktop_applications }}"
