---

- name: Git clone maltego transforms
  ansible.builtin.git:
    repo: "{{ item.r }}"
    dest: "{{ siftrem_toolsetdir }}/maltegotransforms/{{ item.r | basename }}"
    version: "{{ item.v }}"
  with_items: "{{ siftrem_git_maltego }}"
