---

- name: git clone maltego transforms
  git:
    repo: "{{ item.r }}"
    dest: "{{ siftrem_toolsetdir }}/maltegotransforms/"
    version: "{{ item.v }}"
  with_items: "{{ siftrem_git_maltego }}"
