---
# https://www.netresec.com/?page=Blog&month=2014-02&post=HowTo-install-NetworkMiner-in-Ubuntu-Fedora-and-Arch-Linux

- name: Ensure mono is present
  ansible.builtin.package:
    name: mono-devel
    state: present

- name: Download NetworkMiner
  ansible.builtin.get_url:
    url: 'https://www.netresec.com/?download=NetworkMiner'
    dest: "{{ siftrem_toolsetdir }}/NetworkMiner.zip"
    checksum: "sha256:{{ siftrem_networkminer_sha256 }}"
    mode: '0644'

- name: Unarchive NetworkMiner
  ansible.builtin.unarchive:
    src: "{{ siftrem_toolsetdir }}/NetworkMiner.zip"
    dest: /opt
    mode: '0755'
    remote_src: true
    creates: "/opt/{{ siftrem_networkminer_dirname }}/ChangeLog"

- name: Symlink NetworkMiner directory
  ansible.builtin.file:
    src: "/opt/{{ siftrem_networkminer_dirname }}"
    dest: /opt/NetworkMiner
    mode: '0755'
    state: link

- name: Validate NetworkMiner permissions
  ansible.builtin.file:
    path: "{{ item.p }}"
    mode: "{{ item.m }}"
  with_items:
    - { p: /opt/NetworkMiner/NetworkMiner.exe, m: '0755' }
    - { p: /opt/NetworkMiner/AssembledFiles, m: '1777' }
    - { p: /opt/NetworkMiner/AssembledFiles/cache, m: '1777' }
    - { p: /opt/NetworkMiner/Captures, m: '1777' }
