---

- name: add peda to default user gdbinit
  lineinfile:
    dest: "/home/{{ sift_user }}/.gdbinit"
    regexp: "^source {{ siftrem_toolsetdir }}/peda/.*"
    line: "source {{ siftrem_toolsetdir }}/peda/peda.py"
    create: yes
