---

- name: Powershell Empire
  ansible.builtin.git:
    repo: https://github.com/PowerShellEmpire/Empire.git
    dest: "{{ siftrem_toolsetdir }}/empire"
    version: "{{ siftrem_empire_version | default('5aae31e7de591282773d2c8498af04ee4e8778f5') }}"
    force: no
  become: yes
  become_user: "{{ sift_user }}"

## interactive
# - name: Powershell Empire - setup
#   ansible.builtin.command: "./install.sh chdir={{ siftrem_toolsetdir }}/empire/setup"
