---
## create a ramdisk

- name: Ensure ramdisk directory exists
  ansible.builtin.file:
    dest: "{{ ramdisk_path }}"
    mode: '01777'
    state: directory

- name: Ensure ramdisk is mounted
  ansible.builtin.mount:
    name: "{{ ramdisk_path }}"
    src: tmpfs
    fstype: tmpfs
    opts: "size={{ ramdisk_size }}"
    state: mounted
