---
# few adaptation to run latest on unix directly

- name: RegRipper 3.0 | ensure linux setup
  replace:
    dest: "{{ siftrem_toolsetdir }}/RegRipper3.0.git/rip.pl"
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    mode: '0755'
  with_items:
    - { re: ' c:\\perl\\bin\\perl.exe', rep: '/usr/bin/perl' }
    - { re: '^my \$scriptdir = File::Basename::dirname\(\$scriptpath\);', rep: 'my $scriptdir = "{{ siftrem_toolsetdir }}/RegRipper3.0.git/plugins"'}

- name: RegRipper 3.0 | symlink in PATH
  file:
    src: "{{ siftrem_toolsetdir }}/RegRipper3.0.git/rip.pl"
    dest: "/usr/local/bin/rip.pl"
    state: link
    mode: '0755'
