---
- name: git clone binglide
  git:
    repo=https://github.com/volatilityfoundation/volatility.git
    dest={{ siftrem_toolsetdir }}/volatility-win10tp
    version=win10tp
  become: yes
  become_user: "{{ current_user }}"

- name: Check if memory sample already present
  stat: path={{ siftrem_toolsetdir }}/sample/Win10TPx64.vmem.zip
  register: win10m
- name: Win10 memory sample
  get_url: url=https://www.sendspace.com/pro/dl/0cte2h
    dest={{ siftrem_toolsetdir }}/sample/Win10TPx64.vmem.zip
    mode=0400
    owner={{ current_user }}
  when: not win10m.stat.exists

## https://gist.github.com/iMHLv2/8def92d6c3d604273f41
# $ python vol.py --profile=Win10TPx64 -f Win10TPx64.vmem --kdbg=0xf80369db8284 pslist
