---

- name: Test packer playbook
  hosts: all
  vars:
    sift_docker: true
    remnux_docker_enable: true
    ramdisk_size: 2048m
    sift_hostname: 'siftremworkstation'
    sift_user: 'sansforensics'
    # xrdp requires "complex" password
    sift_pass: 'Forensics1234'
    sift_do_x11: false
    sift_webserver: nginx
    remnux_hostname: "{{ sift_hostname }}"
    remnux_user: "{{ sift_user }}"
    remnux_pass: "{{ sift_pass }}"
    remnux_do_x11: true
    remnux_webserver: nginx
    faup_virtualenv_user: "{{ sift_user }}"
    faup_virtualenv_home: "/home/{{ faup_virtualenv_user }}"
    faup_virtualenv_path: "{{ faup_virtualenv_home }}/env-python"
    faup_ownership:
      - { d: /home/sansforensics/.cache/pip, s: directory, m: '0755', o: "{{ sift_user }}" }
      - { d: "{{ toolsetdir }}/faup/src/lib/bindings/python/build", s: directory, m: '0755', o: "{{ sift_user }}" }
      - { d: "{{ toolsetdir }}/faup/src/lib/bindings/python/pyfaup.egg-info", s: directory, m: '0755', o: "{{ sift_user }}" }
    vivisect_virtualenv_user: "{{ sift_user }}"
    vivisect_virtualenv_home: "/home/{{ faup_virtualenv_user }}"
    vivisect_virtualenv_path: "{{ faup_virtualenv_home }}/env-python"
    vivisect_pip: pip3
    vivisect_vcommand: virtualenv3
    vivisect_deps:
      - python3
      - python3-pip
    vivisect_virtualenv:
      - python3-virtualenv
    floss_virtualenv_user: "{{ sift_user }}"
    floss_virtualenv_home: "/home/{{ faup_virtualenv_user }}"
    floss_virtualenv_path: "{{ faup_virtualenv_home }}/env-python"
    floss_pyinstaller_version: 3.3.1
    nodejs_install_npm_user: "root"
    tinyproxy_proxy_url: 'http://localhost:8888'
    tinyproxy_filterdefaultdeny: 'No'
  roles:
    - geerlingguy.docker
    - geerlingguy.nodejs
    - juju4.sift
    - juju4.remnux
    - juju4.siftrem
    - juju4.brim
    - juju4.tinyproxy
    - juju4.xrdp
