# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    #config.vm.box = "centos/7"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
       ansible.groups = {
          "myrole" => ["vsiftrem" ],
       }
    end

    config.vm.define "vsiftrem" do |vsiftrem|
        vsiftrem.vm.hostname = "vsiftrem"
        vsiftrem.vm.provider "virtualbox" do |v|
          v.memory = 2048
        end
    end
    config.vm.synced_folder "/tmp", "/home/vagrant/tmp"
    config.vm.synced_folder "/opt/tmp/security-test/challenges/", "/challenges"
#    config.vm.synced_folder "/tmp", "/home/vagrant/tmp", type: "rsync", rsync__exclude: ".git/"

end

